### ISSUE TITLE
[Question] target_transform=lambda x: 1 means?

### ISSUE THREAD

**Issue by ingbeeedd** [Pangoraw/SemiOrthogonal#2]
Hello, wonder that meaning of target_transform in the process of loading a dataset (ImageFolder). intend?

**Comment by Pangoraw** [comment]
`target_transform` can change the label returned for images but since the labels are not used during training it does nothing:

https://github.com/Pangoraw/SemiOrthogonal/blob/b3b94df6f0987e1c59151c096b71bb9857e97c03/examples/mvtec.py#L108
