### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ingbeeedd** [Pangoraw/SemiOrthogonal#3]
I am testing with datasets that require learning several times through augmentation, not mvtec. 

```python
print(">> Training")
for _ in range(args.epochs):
    for imgs, _ in tqdm(train_dataloader):
        imgs = imgs.to(device)
        semi_orthogonal.train_one_batch(imgs)
mean, cov_inv = semi_orthogonal.finalize_training()
```

First, it is well trained through the code above (k=100)

As a matter of fact, I'm trying to put it on the embedded board, so I'd like to make the performance as small as possible variable `k` (minimizing the pickle dump size).

When epoch is rotated, the selected layer number is fixed due to k

By the way, can I select a new layer for k and combine it with mean and cov that I got before? In other words, can the mean and cov values obtained from the new layers be effective while extremely lowering the k?

Thank you!

**Comment by Pangoraw** [comment]
> can I select a new layer for k

Not sure I understand what this means. To reduce the pickle size you can also try to fit less Gaussian distributions by grouping patches from the same neighborhood to the same Gaussian dividing H and W.
