### ISSUE TITLE
Saving the model embeddings

### ISSUE THREAD

**Issue by mohapatras** [Pangoraw/SemiOrthogonal#4]
Saving the means and covariance resdiuals to disk in form of tensor (.pt) works but screws up the prediction ROC and PRO scores. Is there any efficient way to save the residuals to disk and reload back during inference.

In the documentation, it is mentioned to use the same "trained instance" for the test also.

Thank you

**Comment by jnhwkim** [comment]
Maybe related to the tensor precision? Try to save using a double tensor.

**Comment by mohapatras** [comment]
Ok. I am basically using torch.save and torch.load. Let me check on that. Thanks.

**Comment by mohapatras** [comment]
Tensor precision used is 4 in PyTorch. There is no change.

**Comment by Pangoraw** [comment]
could you show an example of how you save and load the mean and covariance matrices?

I corrected a bug with the loading and added an example, you should be able to do the following:

https://github.com/Pangoraw/SemiOrthogonal/blob/0db2717bf48b5d1a4e046ecffba4cc0b753d8f09/examples/mvtec.py#L112-L120

and get the same performance as without saving.

**Comment by mohapatras** [comment]
@Pangoraw Here is how I was using the mean and covariance inverse tensors.
```
def initialize_embeddings(self):
        "Reload the approx of C^-1"
        means, covs_inv = self.load_embeddings()
        self.means = None
        self.covs = None
        self.covs_inv = covs_inv
        self.real_means = means
```
```
def finalize_training(self):
        "compute the approx of C^-1"
        means, C = self.get_params()
        # free memory
        self.means = None
        self.covs = None
        covs_inv = torch.linalg.inv(C)
        self.covs_inv = covs_inv

        print("Saved Cov Invs")
        torch.save(self.covs_inv, r'C:\SemiOrthogonal-main\embeddings\cov_inv\cov_inv.pt')
        self.real_means = means
        # print("Saved Means")
        torch.save(self.real_means, r'C:\SemiOrthogonal-main\embeddings\means\real_means.pt')
        
        return self.covs_inv, self.real_means
```

```
def load_embeddings(self):
        covs_inv = torch.load(r'C:\SemiOrthogonal-main\embeddings\cov_inv\cov_inv.pt')
        means = torch.load(r'C:\SemiOrthogonal-main\embeddings\means\real_means.pt')
        return means, covs_inv
```

In the mvtec.py file,
```
# print(">> Training")
# for imgs, _ in tqdm(train_dataloader):
#     # print("During semi training size", imgs.shape)
#     imgs = imgs.to(device)
#     semi_orthogonal.train_one_batch(imgs)
# semi_orthogonal.finalize_training()

semi_orthogonal.initialize_embeddings()  # Changed line

n_test_images = len(test_dataset)
print(f">> Testing on {n_test_images} images")
y_trues = []
y_scores = []

amaps = []
masks = []

limited_generator = (x for _, x in zip(range(n_test_images), test_dataset))
# print("before tqdm")

```

Above method does save and load the tensors during inference but the AUCROC and PRO drops to 0.20 and 0.20 from the actual 0.80 and 0.80 respectively.

**Comment by mohapatras** [comment]
> could you show an example of how you save and load the mean and covariance matrices?
> 
> I corrected a bug with the loading and added an example, you should be able to do the following:
> 
> https://github.com/Pangoraw/SemiOrthogonal/blob/0db2717bf48b5d1a4e046ecffba4cc0b753d8f09/examples/mvtec.py#L112-L120
> 
> and get the same performance as without saving.

@Pangoraw Thank you for the suggestion. I will work with the above example you shared.

**Comment by Pangoraw** [comment]
> @Pangoraw Here is how I was using the mean and covariance inverse tensors.

I don't know if it is expected but the path you are saving to is different from the path you are reading from for both cov and means.

**Comment by mohapatras** [comment]
Sorry typo. I have edited and updated the path in above code snippet.

**Comment by mohapatras** [comment]
@Pangoraw Inference performance has increased after using you fix from above. Thank you. Closing this issue.
